#!/usr/bin/env python3
"""Reproduce SafePrompt paper tables from the artifact CSV files.

This script is intentionally deterministic. It reads CSVs in ./data and writes:
  - ./outputs/tables_md/*.md
  - ./outputs/tables_tex/*.tex
"""

from __future__ import annotations

from pathlib import Path
import pandas as pd
import math

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
OUT_MD = ROOT / "outputs" / "tables_md"
OUT_TEX = ROOT / "outputs" / "tables_tex"

def _fmt_pm(mean, std, digits=1, unit=""):
    if mean is None or (isinstance(mean, float) and math.isnan(mean)):
        return "-"
    if std is None or (isinstance(std, float) and math.isnan(std)):
        return f"{mean:.{digits}f}{unit}"
    return f"{mean:.{digits}f}±{std:.{digits}f}{unit}"

def _fmt_int(x):
    if x is None or (isinstance(x, float) and math.isnan(x)):
        return "-"
    return f"{int(x):,}"

def _fmt_pct(x, digits=2):
    if x is None or (isinstance(x, float) and math.isnan(x)):
        return "-"
    return f"{x:.{digits}f}"

def _ensure_dirs():
    OUT_MD.mkdir(parents=True, exist_ok=True)
    OUT_TEX.mkdir(parents=True, exist_ok=True)

def _write_md(name: str, header: str, df: pd.DataFrame):
    path = OUT_MD / f"{name}.md"
    with path.open("w", encoding="utf-8") as f:
        f.write(header.strip() + "\n\n")
        f.write(df.to_markdown(index=False) + "\n")

def _write_tex(name: str, caption: str, label: str, df: pd.DataFrame, colspec: str):
    path = OUT_TEX / f"{name}.tex"
    tex = df.to_latex(index=False, escape=False, column_format=colspec)
    # Replace default rules with booktabs style.
    tex = tex.replace("\\toprule", "\\toprule").replace("\\midrule", "\\midrule").replace("\\bottomrule", "\\bottomrule")
    wrapped = "\n".join([
        "% Auto-generated by scripts/reproduce_tables.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\footnotesize",
        tex.strip(),
        f"\\caption{{{caption}}}",
        f"\\label{{{label}}}",
        "\\end{table}",
        "",
    ])
    path.write_text(wrapped, encoding="utf-8")

def table2_reentrancy():
    raw = pd.read_csv(DATA / "table2_reentrancy_repair.csv")
    df = pd.DataFrame({
        "Dataset": raw["dataset"],
        "Size": raw["size"].map(_fmt_int),
        "Avg. cand./inst": [
            _fmt_pm(m, s, digits=1) for m, s in zip(raw["avg_candidates_mean"], raw["avg_candidates_std"])
        ],
        "Gas Δ (M)": [
            _fmt_pm(m, s, digits=2, unit="") for m, s in zip(raw["gas_delta_M_mean"], raw["gas_delta_M_std"])
        ],
        "Repair time (s)": [
            _fmt_pm(m, s, digits=1) for m, s in zip(raw["repair_time_s_mean"], raw["repair_time_s_std"])
        ],
        "TP/FN": [
            (f"{_fmt_int(tp)}/{_fmt_int(fn)}" if (not math.isnan(tp) if isinstance(tp,float) else True) and (not math.isnan(fn) if isinstance(fn,float) else True) else "-")
            for tp, fn in zip(raw["tp"].fillna(float('nan')), raw["fn"].fillna(float('nan')))
        ],
        "TN/FP": [
            (f"{_fmt_int(tn)}/{_fmt_int(fp)}" if (not math.isnan(tn) if isinstance(tn,float) else True) and (not math.isnan(fp) if isinstance(fp,float) else True) else "-")
            for tn, fp in zip(raw["tn"].fillna(float('nan')), raw["fp"].fillna(float('nan')))
        ],
    })
    _write_md(
        "table2_reentrancy_repair",
        "Table 2 (artifact): Reentrancy repair evaluation reconstructed from CSV.",
        df,
    )
    _write_tex(
        "table2_reentrancy_repair",
        "Reentrancy repair evaluation (from artifact CSV).",
        "tab:artifact-reent",
        df,
        colspec="lrrrrrr",
    )

def table3_price_manip():
    raw = pd.read_csv(DATA / "table3_price_manip_repair.csv")
    df = pd.DataFrame({
        "Dataset": raw["dataset"],
        "Size": raw["size"].map(_fmt_int),
        "Avg. cand./inst": [
            _fmt_pm(m, s, digits=1) for m, s in zip(raw["avg_candidates_mean"], raw["avg_candidates_std"])
        ],
        "Gas Δ (M)": [
            _fmt_pm(m, s, digits=2) for m, s in zip(raw["gas_delta_M_mean"], raw["gas_delta_M_std"])
        ],
        "Repair time (s)": [
            _fmt_pm(m, s, digits=1) for m, s in zip(raw["repair_time_s_mean"], raw["repair_time_s_std"])
        ],
        "TP/FN": [
            (f"{_fmt_int(tp)}/{_fmt_int(fn)}" if (not math.isnan(tp) if isinstance(tp,float) else True) and (not math.isnan(fn) if isinstance(fn,float) else True) else "-")
            for tp, fn in zip(raw["tp"].fillna(float('nan')), raw["fn"].fillna(float('nan')))
        ],
        "TN/FP": [
            (f"{_fmt_int(tn)}/{_fmt_int(fp)}" if (not math.isnan(tn) if isinstance(tn,float) else True) and (not math.isnan(fp) if isinstance(fp,float) else True) else "-")
            for tn, fp in zip(raw["tn"].fillna(float('nan')), raw["fp"].fillna(float('nan')))
        ],
    })
    _write_md(
        "table3_price_manip_repair",
        "Table 3 (artifact): Price-manipulation repair evaluation reconstructed from CSV.",
        df,
    )
    _write_tex(
        "table3_price_manip_repair",
        "Price-manipulation repair evaluation (from artifact CSV).",
        "tab:artifact-pm",
        df,
        colspec="lrrrrrr",
    )

    fp = pd.read_csv(DATA / "table3_fp_breakdown.csv")
    _write_md(
        "table3_fp_breakdown",
        "Table 3 (artifact): False-positive breakdown by category (from CSV).",
        fp,
    )

def table4_reentrancy_comparison():
    raw = pd.read_csv(DATA / "table4_reentrancy_comparison.csv")
    df = pd.DataFrame({
        "System": raw["system"],
        "Role": raw["role"],
        "Time": raw["analysis_or_repair_time"],
        "Flagged": raw["flagged_tp_fp"].map(_fmt_int),
        "Confirmed": raw["confirmed_reentrancy"].map(_fmt_int),
        "Accepted": raw["accepted_repairs"].map(_fmt_int),
        "TP%": raw["tp_percent"].map(_fmt_pct),
        "FP%": raw["fp_percent"].map(_fmt_pct),
    })
    _write_md(
        "table4_reentrancy_comparison",
        "Table 4 (artifact): Reentrancy comparison reconstructed from CSV.",
        df,
    )

def table5_price_manip_comparison():
    raw = pd.read_csv(DATA / "table5_price_manip_comparison.csv")
    df = pd.DataFrame({
        "System": raw["system"],
        "Detected": raw["detected"].map(_fmt_int),
        "Repaired": raw["repaired"].map(_fmt_int),
        "Repair%": raw["repair_percent"].map(lambda x: _fmt_pct(x, digits=2)),
    })
    _write_md(
        "table5_price_manip_comparison",
        "Table 5 (artifact): Price-manipulation comparison (D1) reconstructed from CSV.",
        df,
    )

def table6_ablation():
    raw = pd.read_csv(DATA / "table6_ablation.csv")
    df = pd.DataFrame({
        "Setting": raw["setting"],
        "Acc. repairs": raw["accepted_repairs"].map(_fmt_int),
        "TP%": raw["tp_percent"].map(_fmt_pct),
        "FN%": raw["fn_percent"].map(_fmt_pct),
        "Cand./inst": raw["cand_per_instance"].map(lambda x: _fmt_pct(x, digits=1)),
        "HC TN/FP": [
            f"{_fmt_int(tn)}/{_fmt_int(fp)}" for tn, fp in zip(raw["high_complexity_tn"], raw["high_complexity_fp"])
        ],
        "Reg TN/FP": [
            f"{_fmt_int(tn)}/{_fmt_int(fp)}" for tn, fp in zip(raw["regular_tn"], raw["regular_fp"])
        ],
        "FP%": raw["fp_percent"].map(_fmt_pct),
        "Time (s)": raw["mean_time_s"].map(lambda x: _fmt_pct(x, digits=1)),
    })
    _write_md(
        "table6_ablation",
        "Table 6 (artifact): Ablation results reconstructed from CSV.",
        df,
    )

def table7_readonly():
    raw = pd.read_csv(DATA / "table7_readonly_reentrancy.csv")
    df = pd.DataFrame({
        "Dataset": raw["dataset"],
        "Size": raw["size"].map(_fmt_int),
        "Avg. cand./inst": [
            _fmt_pm(m, s, digits=1) for m, s in zip(raw["avg_candidates_mean"], raw["avg_candidates_std"])
        ],
        "Gas Δ (M)": [
            _fmt_pm(m, s, digits=2) for m, s in zip(raw["gas_delta_M_mean"], raw["gas_delta_M_std"])
        ],
        "Repair time (s)": [
            _fmt_pm(m, s, digits=1) for m, s in zip(raw["repair_time_s_mean"], raw["repair_time_s_std"])
        ],
        "TP/FN": [
            (f"{_fmt_int(tp)}/{_fmt_int(fn)}" if (not math.isnan(tp) if isinstance(tp,float) else True) and (not math.isnan(fn) if isinstance(fn,float) else True) else "-")
            for tp, fn in zip(raw["tp"].fillna(float('nan')), raw["fn"].fillna(float('nan')))
        ],
        "TN/FP": [
            (f"{_fmt_int(tn)}/{_fmt_int(fp)}" if (not math.isnan(tn) if isinstance(tn,float) else True) and (not math.isnan(fp) if isinstance(fp,float) else True) else "-")
            for tn, fp in zip(raw["tn"].fillna(float('nan')), raw["fp"].fillna(float('nan')))
        ],
    })
    _write_md(
        "table7_readonly_reentrancy",
        "Table 7 (artifact): Read-only reentrancy evaluation reconstructed from CSV.",
        df,
    )

def main():
    _ensure_dirs()
    table2_reentrancy()
    table3_price_manip()
    table4_reentrancy_comparison()
    table5_price_manip_comparison()
    table6_ablation()
    table7_readonly()
    print("Wrote tables to outputs/tables_md and outputs/tables_tex")

if __name__ == "__main__":
    main()
